services:
  go:
    container_name: go-chi
    volumes:
      - ./app:/app/
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:3000
    command: sh -c 'go mod tidy && air'
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/init.d:/docker-entrypoint-initdb.d
      - ./.postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ${POSTGRES_DATABASE}
    hostname: postgres
    user: root

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres